<?php
// forms/financial_request_form.php
// ASSUMES HTML skeleton (doctype, head, body) is handled by start_page() in layout_template.php

// You need to manually ensure the <link rel="stylesheet" href="styles.css"> is added
// within the <head> section generated by start_page() or directly in your layout_template.php.
?>
    <div class="container mx-auto p-4 sm:p-8">
        <div class="flex justify-between items-center mb-6 border-b pb-4">
            <h2 class="text-3xl font-extrabold text-gray-800">Submit <?php echo htmlspecialchars($type); ?></h2>
            <p class="text-gray-500">Submitting for: <?php echo htmlspecialchars($_SESSION["org_name"] ?? ''); ?></p>
        </div>

        <?php if (!empty($general_err)): ?>
            <div class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4 mb-6 rounded-lg" role="alert">
                <p class="font-bold">Submission Error</p>
                <p><?php echo $general_err; ?></p>
            </div>
        <?php endif; ?>

        <div class="max-w-4xl mx-auto bg-white p-6 sm:p-10 rounded-xl shadow-2xl">
            <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]) . (!empty($type_param) ? '?type=' . htmlspecialchars($type_param) : ''); ?>" method="post" enctype="multipart/form-data" class="space-y-8">
                
                <input type="hidden" name="type" value="<?php echo htmlspecialchars($type); ?>">
                <?php if (!empty($type_err)): ?>
                    <div class="bg-red-100 border border-red-400 text-red-700 p-3 rounded-lg">
                        <p class="text-sm font-medium">Error: <?php echo $type_err; ?></p>
                    </div>
                <?php endif; ?>

                <div class="space-y-6">
                    <div>
                        <label for="title" class="block text-sm font-medium text-gray-700">Request Title (e.g., Annual Sports Fest Budget)</label>
                        <input type="text" name="title" id="title" 
                                class="mt-1 block w-full px-4 py-2 border rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500 <?php echo (!empty($title_err)) ? 'is-invalid' : 'border-gray-300'; ?>" 
                                value="<?php echo htmlspecialchars($title); ?>" required>
                        <span class="invalid-feedback"><?php echo $title_err; ?></span>
                    </div>

                    <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                        <div>
                            <label class="block text-sm font-medium text-gray-700">Request Type (Selected)</label>
                            <p class="mt-1 block w-full px-4 py-2 bg-gray-100 text-gray-600 rounded-lg shadow-sm border border-gray-300 font-semibold">
                                <?php echo htmlspecialchars($type); ?>
                            </p>
                        </div>

                        <div>
                            <label for="amount" class="block text-sm font-medium text-gray-700">Total Amount (₱)</label>
                            <input type="text" name="amount" id="amount" 
                                class="mt-1 block w-full px-4 py-2 border rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500 <?php echo (!empty($amount_err)) ? 'is-invalid' : 'border-gray-300'; ?>" 
                                value="<?php echo htmlspecialchars($amount_str); ?>" placeholder="e.g. 15000.00" required>
                            <span class="invalid-feedback"><?php echo $amount_err; ?></span>
                        </div>

                        <div>
                            <label for="activity_date" class="block text-sm font-medium text-gray-700">Date of Activity Implementation</label>
                            <input type="date" name="activity_date" id="activity_date" 
                                class="mt-1 block w-full px-4 py-2 border rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500 <?php echo (!empty($activity_date_err)) ? 'is-invalid' : 'border-gray-300'; ?>" 
                                value="<?php echo htmlspecialchars($activity_date); ?>" required>
                            <span class="invalid-feedback"><?php echo $activity_date_err; ?></span>
                        </div>

                        <?php if ($type === 'Liquidation Report' || $type === 'Reimbursement'): ?>
                            <div class="form-group <?php echo (!empty($original_request_id_err)) ? 'has-error' : ''; ?>">
                                <label for="original_request_id">Link to Approved Budget Request</label>
                                <select name="original_request_id" id="original_request_id" class="form-control">
                                    <option value="0">--- Select Original Budget Request ---</option>
                                    <?php 
                                    if (!empty($approved_brs)) {
                                        foreach ($approved_brs as $br) {
                                            $selected = ($param_original_request_id == $br['request_id']) ? 'selected' : '';
                                            echo '<option value="' . htmlspecialchars($br['request_id']) . '" ' . $selected . '>';
                                            echo htmlspecialchars($br['title']) . ' (Approved Amount: ₱' . number_format($br['amount'], 2) . ')</option>';
                                        }
                                    } else {
                                        echo '<option value="0" disabled>No Approved Budget Requests available for liquidation.</option>';
                                    }
                                    ?>
                                </select>
                                <span class="help-block"><?php echo $original_request_id_err; ?></span>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>

                <div id="budget-breakdown-section" class="space-y-4 p-6 border border-gray-200 rounded-xl bg-gray-50/70 shadow-inner">
                    <h3 class="text-2xl font-extrabold text-indigo-700 border-b pb-2">Budget Itemized Breakdown</h3>
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-200">
                            <tr>
                                <th class="px-3 py-2 text-left text-xs font-medium text-gray-700 uppercase tracking-wider w-5/12">Description</th>
                                <th class="px-3 py-2 text-left text-xs font-medium text-gray-700 uppercase tracking-wider w-1/12">Qty</th>
                                <th class="px-3 py-2 text-left text-xs font-medium text-gray-700 uppercase tracking-wider w-2/12">Unit Cost (₱)</th>
                                <th class="px-3 py-2 text-left text-xs font-medium text-gray-700 uppercase tracking-wider w-2/12">Total (₱)</th>
                                <th class="w-1/12"></th>
                            </tr>
                        </thead>
                        <tbody id="budget-items-container" class="bg-white divide-y divide-gray-200">
                        </tbody>
                        <tfoot class="bg-gray-200">
                            <tr>
                                <td colspan="3" class="px-3 py-2 text-right text-base font-bold text-gray-800">Calculated Grand Total:</td>
                                <td class="px-3 py-2 text-left text-base font-bold text-indigo-700" id="calculated-total">₱0.00</td>
                                <td></td>
                            </tr>
                        </tfoot>
                    </table>
                    
                    <div class="flex justify-between items-center pt-2">
                        <button type="button" id="add-item-btn" class="inline-flex items-center px-4 py-2 border border-transparent text-sm leading-4 font-bold rounded-lg shadow-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 transition duration-150">
                            + Add Item
                        </button>
                        <p class="text-xs text-gray-600 text-right">
                            **NOTE:** The Total Amount field at the top should match the Calculated Grand Total.
                        </p>
                    </div>
                </div>

                <div>
                    <label for="description" class="block text-sm font-medium text-gray-700">Detailed Justification / Breakdown</label>
                    <textarea name="description" id="description" rows="6" 
                                class="mt-1 block w-full px-4 py-2 border rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500 <?php echo (!empty($description_err)) ? 'is-invalid' : 'border-gray-300'; ?>" 
                                required><?php echo htmlspecialchars($description); ?></textarea>
                    <span class="invalid-feedback"><?php echo $description_err; ?></span>
                </div>

                <div class="p-5 border border-gray-200 rounded-lg bg-gray-50/70">
                    <label for="supporting_files" class="block text-sm font-medium text-gray-700 mb-2">Supporting Documents (JPEG only)</label>
                    <input type="file" 
                        name="supporting_files[]" 
                        id="supporting_files" 
                        multiple 
                        accept="image/jpeg, .jpeg, .jpg"
                        class="mt-1 block w-full border border-gray-300 rounded-lg p-2 bg-white text-sm <?php echo (!empty($file_err)) ? 'is-invalid' : ''; ?>">
                    <p class="text-xs text-red-500 font-bold mt-1">
                        Only **JPEG/JPG** files are allowed. Max 5MB per file. (Required for Liquidation/Reimbursement)
                    </p>
                    <span class="invalid-feedback"><?php echo $file_err; ?></span>
                </div>

                <div class="pt-4">
                    <button type="submit" class="w-full bg-indigo-600 text-white py-3 rounded-lg text-lg font-semibold hover:bg-indigo-700 transition duration-150 shadow-md transform hover:scale-[1.01] active:scale-95">
                        Submit Request for Approval
                    </button>
                </div>
            </form>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const container = document.getElementById('budget-items-container');
            const addButton = document.getElementById('add-item-btn');
            const totalAmountInput = document.getElementById('amount');
            const calculatedTotalDisplay = document.getElementById('calculated-total');

            function formatCurrency(value) {
                return '₱' + parseFloat(value).toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
            }

            function calculateTotal() {
                let grandTotal = 0;
                const rows = container.querySelectorAll('tr');
                
                rows.forEach(row => {
                    const qtyInput = row.querySelector('[name="item_qty[]"]');
                    const costInput = row.querySelector('[name="item_cost[]"]');
                    const totalCell = row.querySelector('.item-total');

                    let qty = parseInt(qtyInput.value) || 0;
                    let cost = parseFloat(costInput.value.replace(/,/g, '')) || 0.00; 

                    let itemTotal = qty * cost;
                    grandTotal += itemTotal;
                    
                    totalCell.textContent = formatCurrency(itemTotal);
                });

                calculatedTotalDisplay.textContent = formatCurrency(grandTotal);
                totalAmountInput.value = grandTotal.toFixed(2);
            }

            totalAmountInput.addEventListener('blur', function() {
                let value = parseFloat(this.value.replace(/,/g, '')) || 0;
                this.value = value.toFixed(2);
            });


            function createItemRow(description = '', qty = 1, cost = 0.00) {
                const row = document.createElement('tr');
                row.className = 'hover:bg-gray-100 transition duration-100';
                row.innerHTML = `
                    <td class="px-3 py-2 whitespace-nowrap w-5/12">
                        <input type="text" name="item_description[]" value="${description}" class="w-full border-gray-300 rounded-md shadow-sm text-sm focus:border-indigo-500 focus:ring-indigo-500" placeholder="e.g. A4 Paper Ream" required>
                    </td>
                    <td class="px-3 py-2 whitespace-nowrap w-1/12">
                        <input type="number" name="item_qty[]" value="${qty}" min="1" class="item-qty w-full border-gray-300 rounded-md shadow-sm text-sm text-center focus:border-indigo-500 focus:ring-indigo-500" required onchange="calculateTotal()" onkeyup="calculateTotal()">
                    </td>
                    <td class="px-3 py-2 whitespace-nowrap w-2/12">
                        <input type="text" name="item_cost[]" value="${cost.toFixed(2)}" class="item-cost w-full border-gray-300 rounded-md shadow-sm text-sm text-right focus:border-indigo-500 focus:ring-indigo-500" placeholder="0.00" required onchange="calculateTotal()" onkeyup="calculateTotal()">
                    </td>
                    <td class="px-3 py-2 whitespace-nowrap item-total text-sm font-semibold text-gray-900 w-2/12">${formatCurrency(qty * cost)}</td>
                    <td class="px-3 py-2 whitespace-nowrap text-center text-sm font-medium w-1/12">
                        <button type="button" class="remove-item-btn text-red-600 hover:text-red-900" title="Remove Item">
                            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4m-2 4h4m-4 0h-4"></path></svg>
                        </button>
                    </td>
                `;
                
                row.querySelector('.item-cost').addEventListener('blur', function() {
                    let value = parseFloat(this.value.replace(/,/g, '')) || 0;
                    this.value = value.toFixed(2);
                    calculateTotal();
                });

                row.querySelector('.remove-item-btn').addEventListener('click', function() {
                    row.remove();
                    calculateTotal();
                });

                container.appendChild(row);
                calculateTotal();
            }

            addButton.addEventListener('click', () => createItemRow());
            
            createItemRow();
            calculateTotal();
        });
    </script>